import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const meta=JSON.parse(fs.readFileSync(path.join(root,'desktop/package.json'),'utf8'));
const upstream=JSON.parse(fs.readFileSync(path.join(root,'upstream.json'),'utf8'));
if(process.platform!=='darwin')throw new Error('Initial release archive targets macOS only.');
const output=path.join(root,'desktop/release/assets');fs.mkdirSync(output,{recursive:true});
const app=path.join(root,'desktop/release',meta.version,'ER Wiki Community-darwin-'+process.arch,'ER Wiki Community.app');
if(!fs.existsSync(app))throw new Error('Build the community package first.');
const zip=path.join(output,'er-wiki-'+meta.version+'-macos-'+process.arch+'.zip');
execFileSync('ditto',['-c','-k','--sequesterRsrc','--keepParent',app,zip],{stdio:'inherit'});
const source=path.join(output,'er-wiki-'+meta.version+'-source.tar.gz');
execFileSync('git',['archive','--format=tar.gz','--output',source,'HEAD'],{cwd:root});
const renderer=path.join(output,'drawdb-'+upstream.commit+'-source.tar.gz');
execFileSync('git',['archive','--format=tar.gz','--output',renderer,upstream.commit],{cwd:path.join(root,'work/drawdb')});
const hashes=[zip,source,renderer].map(file=>createHash('sha256').update(fs.readFileSync(file)).digest('hex')+'  '+path.basename(file));
fs.writeFileSync(path.join(output,'SHA256SUMS.txt'),hashes.join('\n')+'\n');
console.log(output);
